name: 5.X - FIM on Linux - Integration tests - Tier 0 and 1

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch'
        required: true
        default: 'main'
      build_run_id:
        description: 'Test artifacts from a specific build run (optional, defaults to latest on base_branch)'
        required: false
        default: ''
  pull_request:
    paths:
        - ".github/workflows/5_testintegration_fim-tier-0-1-lin.yml"
        - "src/config/src/syscheck-config.c"
        - "src/config/include/syscheck-config.h"
        - "src/syscheckd/**"
        - "src/Makefile"
        - "tests/integration/conftest.py"
        - "tests/integration/test_fim/**"

# Note: Github will force this by default in June 2026, but we set it explicitly to avoid any issues with JavaScript actions in the meantime.
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test-fim:
    name: FIM integration tests - Tier ${{ matrix.tier }}
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      BRANCH_BASE: ${{ github.base_ref || inputs.base_branch }}
      BUILD_WORKFLOW: 5_builderpackage_agent-linux.yml
      PACKAGES_PATH: /tmp/packages
      AGENT_PACKAGE_REGEXP: wazuh-agent.*amd64.*\.deb
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        tier: [0, 1]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: ".github/workflows/.python-version-it"
          architecture: x64

      - name: Download package artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: ${{ env.BUILD_WORKFLOW }}
          run_id: ${{ inputs.build_run_id }}
          workflow_conclusion: success
          name_is_regexp: true
          name: ${{ env.AGENT_PACKAGE_REGEXP }}
          path: ${{ env.PACKAGES_PATH }}
          if_no_artifact_found: fail
          check_artifacts: true
          search_artifacts: true

      - name: Install and configure wazuh agent
        run: |
          PACKAGE_PATH=$(find "${PACKAGES_PATH}" -maxdepth 2 -type f -name "wazuh-agent*amd64*.deb" | grep -v -E "wazuh-agent-dbg" | head -n 1)
          if [ -z "$PACKAGE_PATH" ]; then
            echo "No agent package found in ${PACKAGES_PATH}"
            exit 1
          fi

          sudo WAZUH_MANAGER="127.0.0.1" dpkg -i "${PACKAGE_PATH}" || sudo apt-get install -f -y

          sudo /var/ossec/bin/wazuh-control stop

          echo "BEFORE"

          sudo cat /var/ossec/etc/ossec.conf

          sudo awk '
            BEGIN { first_close_seen=0 }
            /<\/ossec_config>/ {
              if (!first_close_seen) { first_close_seen=1; next }  # skip first closing tag
            }
            /<ossec_config>/ {
              if (first_close_seen) { first_close_seen=2; next }   # skip next opening tag
            }
            { print }
          ' /var/ossec/etc/ossec.conf > /tmp/ossec.conf.fixed && sudo mv /tmp/ossec.conf.fixed /var/ossec/etc/ossec.conf

          sudo awk '
            /<rootcheck>/ { in_block=1; print; next }
            /<\/rootcheck>/ && in_block { in_block=0; print "    <disabled>yes</disabled>"; print; next }
            in_block { next }
            { print }
          ' /var/ossec/etc/ossec.conf > /tmp/ossec.conf.fixed && sudo mv /tmp/ossec.conf.fixed /var/ossec/etc/ossec.conf

          sudo awk '
            /<syscheck>/ { in_block=1; print; next }
            /<\/syscheck>/ && in_block { in_block=0; print "    <disabled>yes</disabled>"; print; next }
            in_block { next }
            { print }
          ' /var/ossec/etc/ossec.conf > /tmp/ossec.conf.fixed && sudo mv /tmp/ossec.conf.fixed /var/ossec/etc/ossec.conf

          echo "AFTER"

          sudo cat /var/ossec/etc/ossec.conf

          sudo /var/ossec/bin/wazuh-control start

      # Download and install integration tests framework.
      - name: Download and install integration tests framework
        run: |
          VERSION="$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' VERSION.json)"
          if [ "X`git ls-remote https://github.com/wazuh/qa-integration-framework.git ${BRANCH_NAME}`" != "X" ]; then
              QA_BRANCH=${BRANCH_NAME}
          elif [ "X`git ls-remote https://github.com/wazuh/qa-integration-framework.git ${BRANCH_BASE}`" != "X" ]; then
              QA_BRANCH=${BRANCH_BASE}
          elif [ "X`git ls-remote https://github.com/wazuh/qa-integration-framework.git ${VERSION}`" != "X" ]; then
              QA_BRANCH=${VERSION}
          else
              QA_BRANCH="main"
          fi
          git clone -b ${QA_BRANCH} --single-branch https://github.com/wazuh/qa-integration-framework.git
          sudo pip install qa-integration-framework/
          sudo rm -rf qa-integration-framework/
      # Install audit required by FIM
      - name: Install audit
        run: |
          sudo apt-get update
          sudo apt-get install auditd -y
      # Run fim integration tests.
      - name: Run fim integration tests
        run: |
          cd tests/integration
          sudo GITHUB_SHA="${{ github.sha }}" GITHUB_REF_NAME="${BRANCH_NAME}" python -m pytest --tier ${{ matrix.tier }} test_fim/ --html=results.html --self-contained-html
      # Upload the tests result html as an artifact
      - name: Upload failed test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: fim-tier-${{ matrix.tier }}-lin-test-results-${{ github.run_id }}
          path: ./tests/integration/results.html
          retention-days: 7
